name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Build
        run: |
          npm ci
          npm run export

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          token: ${{ secrets.DGGD }}
          branch: gh-pages
          folder: out
          clean: true